# Generated by Django 5.0.11 on 2025-02-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destinations_created_at_destinations_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='images',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='media/destinations'),
        ),
    ]
