# Generated by Django 5.0.11 on 2025-02-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_destinations_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/destinations'),
        ),
    ]
