# Generated by Django 5.0.11 on 2025-02-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_destinations_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
