# Generated by Django 5.0.11 on 2025-02-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_destinations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/tours'),
        ),
    ]
